/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LookiSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/looki.ts
var import_obsidian = require("obsidian");
var LookiClient = class {
  constructor(apiKey, baseUrl) {
    this.apiKey = apiKey;
    this.baseUrl = baseUrl;
  }
  async get(path, params) {
    const url = new URL(this.baseUrl.replace(/\/$/, "") + path);
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        if (v !== null && v !== void 0) url.searchParams.set(k, String(v));
      }
    }
    const resp = await (0, import_obsidian.requestUrl)({
      url: url.toString(),
      method: "GET",
      headers: { "x-api-key": this.apiKey }
    });
    if (resp.status >= 400) {
      throw new Error(`Looki API ${resp.status}: ${resp.text}`);
    }
    const text = resp.text || "";
    return text ? JSON.parse(text) : {};
  }
  async momentsOnDate(date) {
    var _a;
    const data = await this.get("/moments", { on_date: date });
    return extractList((_a = data == null ? void 0 : data.data) != null ? _a : data, "moments");
  }
  async momentFiles(id) {
    var _a, _b, _c;
    const data = await this.get(`/moments/${id}/files`, { limit: 50 });
    const d = (_a = data == null ? void 0 : data.data) != null ? _a : data;
    if (Array.isArray(d)) return d;
    const obj = d;
    return (_c = (_b = obj == null ? void 0 : obj.items) != null ? _b : obj == null ? void 0 : obj.files) != null ? _c : [];
  }
  async forYou(recordedFrom, limit = 50, cursorId) {
    var _a, _b;
    const data = await this.get("/for_you/items", {
      recorded_from: recordedFrom,
      limit,
      cursor_id: cursorId
    });
    const d = (_a = data == null ? void 0 : data.data) != null ? _a : data;
    const items = extractList(d, "items");
    const cursor = (_b = d == null ? void 0 : d.cursor_id) != null ? _b : data == null ? void 0 : data.cursor_id;
    return { items, cursorId: cursor };
  }
};
function extractList(data, key) {
  if (Array.isArray(data)) return data;
  if (data && typeof data === "object") {
    const obj = data;
    if (key && Array.isArray(obj[key])) return obj[key];
    for (const k of ["moments", "items", "for_you", "for_you_items", "data"]) {
      if (Array.isArray(obj[k])) return obj[k];
    }
  }
  return [];
}
function parseLocation(loc) {
  if (!loc) return "";
  if (typeof loc === "object" && loc !== null) {
    const o = loc;
    const parts = [o.administrativeArea, o.subAdministrativeArea, o.locality, o.subLocality, o.street, o.name].filter((p) => typeof p === "string" && p.length > 0);
    return parts.join(" ");
  }
  if (typeof loc === "string") {
    const s = loc.trim();
    if (s.startsWith("{")) {
      try {
        return parseLocation(JSON.parse(s));
      } catch (e) {
      }
    }
    return s;
  }
  return String(loc);
}
var MD_EXT_IMG = /!\[[^\]]*\]\(https?:\/\/[^)]+\)/g;
function sanitizeContent(text) {
  if (!text) return "";
  return text.replace(MD_EXT_IMG, "").trim();
}
function dateOf(iso) {
  if (!iso) return null;
  return iso.slice(0, 10);
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var LookiSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const s = this.plugin.settings;
    new import_obsidian2.Setting(containerEl).setName("\u8BBE\u7F6E").setHeading();
    new import_obsidian2.Setting(containerEl).setName("API Key").setDesc("Looki \u5F00\u653E API \u5BC6\u94A5\uFF0C\u5F62\u5982 lk-xxxx").addText(
      (t) => t.setPlaceholder("lk-...").setValue(s.apiKey).onChange(async (v) => {
        s.apiKey = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API Base URL").setDesc("\u9ED8\u8BA4 https://open.looki.tech/api/v1").addText(
      (t) => t.setPlaceholder("https://open.looki.tech/api/v1").setValue(s.baseUrl).onChange(async (v) => {
        s.baseUrl = v.trim() || "https://open.looki.tech/api/v1";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u76EE\u6807\u6587\u4EF6\u5939").setDesc("\u6BCF\u65E5\u8BB0\u5FC6\u7B14\u8BB0\u5199\u5165\u7684 vault \u5185\u76F8\u5BF9\u8DEF\u5F84").addText(
      (t) => t.setPlaceholder("Looki/\u6BCF\u65E5\u8BB0\u5FC6").setValue(s.notesFolder).onChange(async (v) => {
        s.notesFolder = v.trim() || "Looki/\u6BCF\u65E5\u8BB0\u5FC6";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5A92\u4F53\u6587\u4EF6\u5939").setDesc("\u56FE\u7247/\u89C6\u9891\u4E0B\u8F7D\u4FDD\u5B58\u7684 vault \u5185\u76F8\u5BF9\u8DEF\u5F84\uFF08\u5A92\u4F53\u5F00\u5173\u5F00\u542F\u65F6\u751F\u6548\uFF09").addText(
      (t) => t.setPlaceholder("Looki/media").setValue(s.mediaFolder).onChange(async (v) => {
        s.mediaFolder = v.trim() || "Looki/media";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u56FE\u7247").setDesc("\u4E0B\u8F7D Looki \u56FE\u7247 (IMAGE) \u5230 vault \u5E76\u7528 ![[...]] \u5D4C\u5165\u7B14\u8BB0").addToggle(
      (t) => t.setValue(s.syncImages).onChange(async (v) => {
        s.syncImages = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u89C6\u9891").setDesc("\u4E0B\u8F7D Looki \u89C6\u9891 (VIDEO) \u5230 vault \u5E76\u5D4C\u5165\uFF08\u4F53\u79EF\u8F83\u5927\uFF0C\u9ED8\u8BA4\u5173\u95ED\uFF09").addToggle(
      (t) => t.setValue(s.syncVideos).onChange(async (v) => {
        s.syncVideos = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u56DE\u586B\u5929\u6570").setDesc("\u6BCF\u6B21\u540C\u6B65\u989D\u5916\u8865\u6700\u8FD1 N \u5929\u7684\u65E5\u5E38\u4E0E\u5373\u65F6\u63D0\u793A\uFF08\u517C\u987E\u5EF6\u8FDF\u751F\u6210\u7684\u5185\u5BB9\uFF09").addText(
      (t) => t.setPlaceholder("1").setValue(String(s.backfillDays)).onChange(async (v) => {
        const n = parseInt(v) || 0;
        s.backfillDays = n;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u81EA\u52A8\u540C\u6B65\u95F4\u9694\uFF08\u5206\u949F\uFF09").setDesc("0 = \u5173\u95ED\u81EA\u52A8\u540C\u6B65\u3002\u5EFA\u8BAE 30").addText(
      (t) => t.setPlaceholder("30").setValue(String(s.syncInterval)).onChange(async (v) => {
        const n = parseInt(v) || 0;
        s.syncInterval = n;
        await this.plugin.saveSettings();
        this.plugin.restartAutoSync();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u542F\u52A8\u65F6\u81EA\u52A8\u540C\u6B65").setDesc("Obsidian \u6253\u5F00\u65F6\u7ACB\u5373\u540C\u6B65\u4E00\u6B21").addToggle(
      (t) => t.setValue(s.syncOnStartup).onChange(async (v) => {
        s.syncOnStartup = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").addButton(
      (b) => b.setButtonText("\u6D4B\u8BD5").onClick(async () => {
        try {
          await this.plugin.testConnection();
          this.plugin.notice("\u8FDE\u63A5\u6210\u529F \u2705");
        } catch (e) {
          this.plugin.notice("\u8FDE\u63A5\u5931\u8D25\uFF1A" + e.message);
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u7ACB\u5373\u540C\u6B65").addButton(
      (b) => b.setButtonText("\u540C\u6B65 Now").setCta().onClick(async () => {
        await this.plugin.syncNow();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5168\u91CF\u91CD\u7F6E\u5E76\u91CD\u65B0\u540C\u6B65").setDesc("\u6E05\u7A7A\u540C\u6B65\u8BB0\u5F55\uFF0C\u91CD\u65B0\u62C9\u53D6\u5168\u90E8\u5386\u53F2").addButton(
      (b) => b.setButtonText("\u5168\u91CF\u91CD\u540C\u6B65").onClick(async () => {
        await this.plugin.fullResync();
      })
    );
  }
};

// src/main.ts
var DEFAULT_BASE = "https://open.looki.tech/api/v1";
var DEFAULT_NOTES = "Looki/\u6BCF\u65E5\u8BB0\u5FC6";
var DEFAULT_MEDIA = "Looki/media";
var DEFAULT_SETTINGS = {
  apiKey: "",
  baseUrl: DEFAULT_BASE,
  notesFolder: DEFAULT_NOTES,
  mediaFolder: DEFAULT_MEDIA,
  syncImages: true,
  syncVideos: false,
  backfillDays: 1,
  syncInterval: 30,
  syncOnStartup: false
};
var LookiSyncPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.autoTimer = null;
    this.statusBar = null;
  }
  async onload() {
    await this.loadDataAll();
    this.addSettingTab(new LookiSettingTab(this.app, this));
    this.addRibbonIcon("refresh-cw", "Looki Sync", () => this.syncNow());
    this.addCommand({ id: "sync-now", name: "Sync now", callback: () => this.syncNow() });
    this.addCommand({
      id: "full-resync",
      name: "Full resync (reset history)",
      callback: () => this.fullResync()
    });
    this.statusBar = this.addStatusBarItem();
    this.updateStatusBar("\u5C31\u7EEA");
    if (this.settings.syncOnStartup) await this.syncNow();
    this.restartAutoSync();
  }
  onunload() {
    this.stopAutoSync();
  }
  // ---------- 数据读写 ----------
  async loadDataAll() {
    var _a, _b, _c;
    const loaded = (_a = await this.loadData()) != null ? _a : {};
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_b = loaded.settings) != null ? _b : {});
    this.state = Object.assign(
      { syncedMoments: {}, syncedForYou: {}, lastRun: null },
      (_c = loaded.state) != null ? _c : {}
    );
  }
  async saveSettings() {
    await this.saveData({ settings: this.settings, state: this.state });
  }
  async saveDataAll() {
    await this.saveData({ settings: this.settings, state: this.state });
  }
  notice(msg) {
    new import_obsidian3.Notice(msg);
  }
  // ---------- 同步入口 ----------
  async syncNow() {
    var _a;
    if (!this.settings.apiKey) {
      this.notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 Looki API Key");
      return;
    }
    this.updateStatusBar("\u540C\u6B65\u4E2D\u2026");
    try {
      const client = new LookiClient(this.settings.apiKey, this.settings.baseUrl);
      const dates = this.targetDates();
      const forYouByDate = await this.fetchForYouGrouped(client, dates[dates.length - 1]);
      let total = 0;
      for (const date of dates) {
        const fy = (_a = forYouByDate.get(date)) != null ? _a : [];
        total += await this.syncDay(client, date, fy);
      }
      this.state.lastRun = (/* @__PURE__ */ new Date()).toISOString();
      await this.saveDataAll();
      this.updateStatusBar(`\u5DF2\u540C\u6B65 ${total}`);
      this.notice(`Looki \u540C\u6B65\u5B8C\u6210\uFF1A${total} \u6761`);
    } catch (e) {
      this.updateStatusBar("\u540C\u6B65\u5931\u8D25");
      this.notice("\u540C\u6B65\u5931\u8D25\uFF1A" + e.message);
      console.error("Looki Sync error:", e);
    }
  }
  async fullResync() {
    this.state = { syncedMoments: {}, syncedForYou: {}, lastRun: null };
    await this.saveDataAll();
    this.notice("\u5DF2\u91CD\u7F6E\u540C\u6B65\u8BB0\u5F55\uFF0C\u5F00\u59CB\u5168\u91CF\u91CD\u540C\u6B65\u2026");
    await this.syncNow();
  }
  async testConnection() {
    if (!this.settings.apiKey) throw new Error("\u672A\u586B\u5199 API Key");
    const client = new LookiClient(this.settings.apiKey, this.settings.baseUrl);
    await client.momentsOnDate(this.fmt(/* @__PURE__ */ new Date()));
  }
  // ---------- 单日合并同步 ----------
  async syncDay(client, date, foryouItems) {
    await this.ensureFolder(this.settings.notesFolder);
    const moments = await client.momentsOnDate(date);
    const mBlocks = [];
    for (const m of moments) {
      const embeds = await this.downloadMedia(client, m.id, date);
      mBlocks.push(this.momentBlock(m, embeds));
    }
    const fBlocks = [];
    for (const it of foryouItems) {
      const embeds = await this.downloadForYouMedia(it, date);
      fBlocks.push(this.foryouBlock(it, embeds));
    }
    if (!mBlocks.length && !fBlocks.length) {
      console.log(`[looki] ${date} \u65E0\u6570\u636E`);
      return 0;
    }
    const content = this.buildNote(date, mBlocks, fBlocks);
    const path = `${this.settings.notesFolder}/${date}.md`;
    await this.app.vault.adapter.write(path, content);
    for (const m of moments) if (m.id) this.state.syncedMoments[m.id] = date;
    for (const it of foryouItems) if (it.id) this.state.syncedForYou[it.id] = date;
    await this.saveDataAll();
    return mBlocks.length + fBlocks.length;
  }
  // ---------- 媒体下载 ----------
  async downloadMedia(client, momentId, date) {
    if (!this.settings.syncImages && !this.settings.syncVideos) return [];
    const files = await client.momentFiles(momentId);
    const embeds = [];
    let i = 0;
    for (const f of files) {
      const file = f.file;
      if (!(file == null ? void 0 : file.temporary_url)) continue;
      const mt = (file.media_type || "").toUpperCase();
      if (mt === "IMAGE" && !this.settings.syncImages) continue;
      if (mt === "VIDEO" && !this.settings.syncVideos) continue;
      if (mt !== "IMAGE" && mt !== "VIDEO") continue;
      i++;
      const kind = mt === "VIDEO" ? "video" : "image";
      const relBase = `${this.settings.mediaFolder}/${date}/${momentId}_${i}`;
      const emb = await this.downloadOne(file.temporary_url, relBase, kind);
      if (emb) embeds.push(emb);
    }
    return embeds;
  }
  async downloadForYouMedia(it, date) {
    if (!this.settings.syncImages) return [];
    const cover = it.cover;
    if ((cover == null ? void 0 : cover.media_type) === "IMAGE" && cover.temporary_url) {
      const relBase = `${this.settings.mediaFolder}/${date}/${it.id}_cover`;
      const emb = await this.downloadOne(cover.temporary_url, relBase, "image");
      if (emb) return [emb];
    }
    return [];
  }
  async downloadOne(url, relBase, kind) {
    var _a;
    try {
      let ext = extFromUrl(url);
      const relFromUrl = ext ? `${relBase}.${ext}` : "";
      if (relFromUrl && await this.app.vault.adapter.exists(relFromUrl))
        return this.mediaEmbed(relFromUrl, kind);
      const resp = await (0, import_obsidian3.requestUrl)({ url, method: "GET" });
      if (resp.status >= 400) throw new Error("HTTP " + resp.status);
      if (!ext) {
        const ct = resp.headers && (resp.headers["content-type"] || resp.headers["Content-Type"]) || "";
        ext = (_a = extFromContentType(String(ct).toLowerCase())) != null ? _a : kind === "video" ? "mp4" : "jpg";
      }
      const relPath = `${relBase}.${ext}`;
      await this.ensureFolder(this.dirname(relPath));
      await this.app.vault.adapter.writeBinary(relPath, resp.arrayBuffer);
      return this.mediaEmbed(relPath, kind);
    } catch (e) {
      console.warn("Looki \u5A92\u4F53\u4E0B\u8F7D\u5931\u8D25", url, e);
      return null;
    }
  }
  mediaEmbed(relPath, kind) {
    const icon = kind === "video" ? "\u{1F3AC}" : "\u{1F5BC}\uFE0F";
    return `${icon} ![[${relPath}]]`;
  }
  dirname(p) {
    const idx = p.lastIndexOf("/");
    return idx >= 0 ? p.slice(0, idx) : "";
  }
  async ensureFolder(folder) {
    if (!folder) return;
    const parts = folder.split("/").filter(Boolean);
    let cur = "";
    for (const p of parts) {
      cur = cur ? `${cur}/${p}` : p;
      if (!await this.app.vault.adapter.exists(cur)) {
        try {
          await this.app.vault.adapter.mkdir(cur);
        } catch (e) {
        }
      }
    }
  }
  // ---------- 数据获取辅助 ----------
  targetDates() {
    const out = [];
    const today = /* @__PURE__ */ new Date();
    for (let i = 0; i <= this.settings.backfillDays; i++) {
      const d = new Date(today);
      d.setDate(d.getDate() - i);
      out.push(this.fmt(d));
    }
    return out;
  }
  async fetchForYouGrouped(client, sinceDate) {
    const map = /* @__PURE__ */ new Map();
    const seen = /* @__PURE__ */ new Set();
    let cursor;
    do {
      const { items, cursorId } = await client.forYou(sinceDate, 50, cursor);
      for (const it of items) {
        if (!it.id || seen.has(it.id)) continue;
        seen.add(it.id);
        const d = dateOf(it.recorded_at || it.created_at) || this.fmt(/* @__PURE__ */ new Date());
        if (!map.has(d)) map.set(d, []);
        map.get(d).push(it);
      }
      cursor = cursorId;
    } while (cursor);
    return map;
  }
  // ---------- 笔记渲染 ----------
  momentBlock(m, embeds) {
    const id = m.id || "";
    const title = m.title || "(\u65E0\u6807\u9898)";
    const start = m.start_time || m.created_at || "";
    const end = m.end_time || "";
    const loc = parseLocation(m.location);
    const desc = m.description || "";
    const media = (m.media_types || []).join(", ") || "\u2014";
    const lines = [`### ${title}  \`id:${id}\``];
    if (start) lines.push(`- \u65F6\u95F4: ${start}` + (end ? ` \u2192 ${end}` : ""));
    if (loc) lines.push(`- \u5730\u70B9: ${loc}`);
    lines.push(`- \u5A92\u4F53: ${media}`);
    if (desc) lines.push(`- \u63CF\u8FF0: ${desc}`);
    for (const e of embeds) lines.push(e);
    lines.push("");
    return lines.join("\n");
  }
  foryouBlock(it, embeds) {
    const id = it.id || "";
    const type = it.type || "FOR_YOU";
    const title = it.title || "(\u65E0\u6807\u9898)";
    const recorded = it.recorded_at || it.created_at || "";
    const desc = it.description || "";
    const content = sanitizeContent(it.content);
    const lines = [`### ${title}  \`[${type}]\`  \`id:${id}\``];
    if (recorded) lines.push(`- \u8BB0\u5F55\u4E8E: ${recorded}`);
    if (desc) lines.push(`- \u7B80\u4ECB: ${desc}`);
    for (const e of embeds) lines.push(e);
    if (content) {
      lines.push("");
      lines.push(content);
    }
    lines.push("");
    return lines.join("\n");
  }
  buildNote(date, mBlocks, fBlocks) {
    const title = `Looki \u6BCF\u65E5\u8BB0\u5FC6 ${date}`;
    const header = `---
title: "${title}"
created: ${date}
updated: ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 19)}
tags:
  - looki
  - looki/daily
  - looki/foryou
source: looki
date: ${date}
---

# Looki \u6BCF\u65E5\u8BB0\u5FC6 \xB7 ${date}

`;
    let body = "";
    if (mBlocks.length) body += "## \u4ECA\u65E5\u7247\u6BB5 (Moments)\n\n" + mBlocks.join("\n") + "\n\n";
    if (fBlocks.length) body += "## \u5373\u65F6\u63D0\u793A (For You)\n\n" + fBlocks.join("\n") + "\n";
    return header + body;
  }
  // ---------- 自动同步 ----------
  restartAutoSync() {
    this.stopAutoSync();
    if (this.settings.syncInterval > 0) {
      this.autoTimer = window.setInterval(
        () => this.syncNow(),
        this.settings.syncInterval * 60 * 1e3
      );
    }
  }
  stopAutoSync() {
    if (this.autoTimer !== null) {
      window.clearInterval(this.autoTimer);
      this.autoTimer = null;
    }
  }
  updateStatusBar(text) {
    if (this.statusBar) this.statusBar.setText("Looki: " + text);
  }
  fmt(d) {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
};
function extFromUrl(url) {
  try {
    const base = new URL(url).pathname.split("/").pop() || "";
    const m = base.match(/\.([a-z0-9]+)$/i);
    if (m) {
      const e = m[1].toLowerCase();
      return e === "jpeg" ? "jpg" : e;
    }
  } catch (e) {
  }
  return null;
}
function extFromContentType(ct) {
  if (ct.includes("png")) return "png";
  if (ct.includes("jpeg") || ct.includes("jpg")) return "jpg";
  if (ct.includes("webp")) return "webp";
  if (ct.includes("heic") || ct.includes("heif")) return "heic";
  if (ct.includes("gif")) return "gif";
  if (ct.includes("mp4")) return "mp4";
  if (ct.includes("quicktime") || ct.includes("mov")) return "mov";
  return null;
}
